// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW5hvmYbuK1lUytmDfChGwNvy-MHJx8v4',
    appId: '1:90817220770:web:67916ef74bdbe6576b07fb',
    messagingSenderId: '90817220770',
    projectId: 'easyshopping-92614',
    authDomain: 'easyshopping-92614.firebaseapp.com',
    storageBucket: 'easyshopping-92614.firebasestorage.app',
    measurementId: 'G-8GRVC3HV10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS9tgqgrbOejt1vQnueGwInXw8KpLizVw',
    appId: '1:90817220770:android:3de3f50317ad0d516b07fb',
    messagingSenderId: '90817220770',
    projectId: 'easyshopping-92614',
    storageBucket: 'easyshopping-92614.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk-vz0HycPrhhB5Zcs6tqJ5Ais8yiu8OA',
    appId: '1:90817220770:ios:ff54b975f04835416b07fb',
    messagingSenderId: '90817220770',
    projectId: 'easyshopping-92614',
    storageBucket: 'easyshopping-92614.firebasestorage.app',
    iosBundleId: 'com.example.eCommeceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk-vz0HycPrhhB5Zcs6tqJ5Ais8yiu8OA',
    appId: '1:90817220770:ios:ff54b975f04835416b07fb',
    messagingSenderId: '90817220770',
    projectId: 'easyshopping-92614',
    storageBucket: 'easyshopping-92614.firebasestorage.app',
    iosBundleId: 'com.example.eCommeceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW5hvmYbuK1lUytmDfChGwNvy-MHJx8v4',
    appId: '1:90817220770:web:2824d099272ff39d6b07fb',
    messagingSenderId: '90817220770',
    projectId: 'easyshopping-92614',
    authDomain: 'easyshopping-92614.firebaseapp.com',
    storageBucket: 'easyshopping-92614.firebasestorage.app',
    measurementId: 'G-BJYSJH0PSY',
  );
}
